uploads = []

[[generated]]
id = "kk6bVCVtv9q2t-Y9BYZo9"
uri = "file://artifacts/bloxblitz-bot/public/hero-network.png"
type = "image"
title = "Abstract glowing network nodes"

[[generated]]
id = "R1DXRPjPi1GpJVQfGTHE7"
uri = "file://artifacts/bloxblitz-bot/public/security-lock.png"
type = "image"
title = "Glowing neon lock"

[[outputs]]
id = "XxxnwIOzAAhTJpnfMMDdO"
uri = "file://bot-source.tar.gz"
type = "unspecified"
title = "Bot Source Files (index, app, bot, lib, routes)"

[[outputs]]
id = "x5sAv7O6RCGNJVi0xILzf"
uri = "file://bot-code.tar.gz"
type = "unspecified"
title = "bot.ts — BloxBlitz MM Bot source code"
